import React from "react";
const data={
    "Aleena":'Aleena Rais, originating from Lucknow, transitioned from corporate life to become a prominent educator. With a part-time teaching role and a thriving presence on YouTube and Instagram, she has amassed a following of 5 million on YouTube and 1.2 million on Instagram, showcasing her achievements in educating millions on subjects ranging from English to personality development.',
    "sangwan":'Capt Satendra Sangwan was the leader of the first platoon to go for the Kargil war in Batalik sector. Despite losing his right leg in battle, he excelled in Athletics and Badminton at National and International levels, winning accolades including the Asian and World Games in 2009. He was honored with the prestigious National  Award from the President of India for being the role model for the society. In 2017, he made history by guiding the ONGC team for expedition to Mount Everest with a prosthetic limb, marking the first independent corporate team to successfully summit within a brief span of 15 months.',
    "Rajat":"Rajat Rathor, a man of many talents, has been serving the streets of Delhi as a dedicated cop for six years now. He's not just any cop; he's the cop who's become a sensation on social media platforms, captivating audiences with his unique blend of duty and melody. He gained recognition nationwide when he was selected as a standout contestant in Indian Idol 14. His popularity transcends boundaries, resonating with young minds eager for inspiration and change.",
    "Mrinal":"Mrinal Talukdar, a stalwart in Assam journalism for over 35 years, has left an indelible mark across print, news agency, television, and digital platforms. Renowned as an author, filmmaker, and planter, he is celebrated for digitizing Assam's rich history from 1813 onward. Additionally, he founded the unique Folk Tea festival, blending folk music and adventure in tea gardens. Talukdar's multifaceted contributions have earned him multiple awards and accolades.",
    "Asutosh": "Meet Asutosh Kashyap, founder of Utpaat Vision and Creations, a visionary filmmaker known for 16 years of immersive storytelling across mediums. His work, including the acclaimed 'Sijou,' showcased at IFFI52, sheds light on diverse narratives like the Indo-Bhutan border's feudal system. Not stopping there, Asutosh braved a 10-day expedition in Sibuk and sailed perilous waters to protect river ecosystems. As an ambassador for Canon, his advocacy knows no bounds, making his mark through artistry and adventure.",
    "Rituparna":"TEDxIITGuwahati brings to you the opportunity to meet Ms Rituparna Neog whose pronouns are she and they. Ms Rituparna is the Associate Vice Chairperson of State Transgender Welfare Board, Government of Assam. She is a story teller, founder & director of Akam Foundation and is actively working on Free Community Library for all. Many of you may have watched her YouTube podcasts. She is an excellent orator and a young torch bearer of education among transgender community.",
    "illina":"Ilina Sinha, a PhD student in Computer Science impressed the team with her unique talk idea where she will be talking about the death of a language and will discuss the value of connecting to one's roots through poetry and other forms of creativity. She herself is a speaker of an endangered 'Bishnupriya Manipuri' language. She will be one of the 8 speakers for our event. We can't wait to hear her 'ideas worth spreading'.",
    "Sudhana":"Sudhana Sankar is a Bharatanatyam artiste, teacher, model and an aspiring actor. She is a senior disciple of Late Padma Bhushan Guru Dr. Saroja Vaidyanathan and Guru Rama Vaidyanathan. She has  been a graded artiste with Doordarshan India, national scholarship holder from the Ministry of culture India.  Currently, she is expanding her creative horizons by delving into the world of storytelling through Instagram videos, where she is carving out a distinctive niche for herself."
}
export default data;