import React from 'react'

const speaker2023Data = {
    Divanshu: 'Divanshu Kumar is a mechanical engineering graduate from IIT Madras and an entrepreneur who is passionate about solving real life problems using first principle thinking. He is Co-founder & CEO of Solinas Integrity which got Best “On Campus Award” in ET Startup awards 2022. He is also Co-founder of Involve Learning Solutions Foundation, an international award winning organization with a vision to develop a sense of agency in school students. He was one of the delegates to represent India at Global Engagement Summit 2017 at Chicago.',
    Kamal: "Kamal Jeswani is an International Speaker and also India's 1st Internationally Certified Financial Success Coach with a CFP and MBA in Finance. Some more of his qualifications and certifications include B.com, QPFP, MBA in Retail Operations, Emotional Intelligence Expert etc. He helps working professionals create secured wealth with his powerful PMG 5.0 model, without sacrificing a good lifestyle. He has been conducting Financial Super Success seminars across India and also trains employees of elite companies like Times of India, Raymond, Welspun, Tata group company, Rotaract club, HR Association of India, etc.",
    Neeraj: 'Dr Neeraj Sharma is an assistant professor at the School of Data Science and Artificial Intelligence at the Indian Institute of Technology, Guwahati (India). He is also an engineer, scientist and researcher. His research interests include understanding of audio (bio-acoustics, health-acoustics, speech and music); Brain-informed signal processing (behavioural and EEG data capture and analysis); AI for human-machine interaction (perception and cognition); Non-stationary time-series signal modelling. After his B.tech from College of Engineering and Technology, Bhubaneswar, he received his PhD and Masters from Indian Institute of Science, Bangalore. He was a post-doctoral researcher at the Neuroscience Institute Psychology Dept. at Carnegie Mellon University (CMU), Pittsburgh. He had also been a scientist at the Fraunhofer Institute for Integrated Circuits, IIS in Erlangen (Germany).',
    Neil: `Neil D'Silva (Author, Screenwriter) The forerunner of contemporary Indian horror literature. He has been named one of the "Top 7 Indian Horror Writers" to be read by the UK’s DESIblitz magazine. The founder and creative director of Litventure. His unique stories have struck a chord with a wide range of readers, eliciting praise from various quarters. YAKSHINI is one of his most satisfying inventions. He is the best-selling author of several novels, including Maya's New Husband, which was named Entertainer of the Year at the 2015 Literary Awards, and Haunted: Real-Life Encounters with Ghosts and Spirits.`,
    Plabita: `Plabita Borthakur made her debut in PK as Anushka Sharma's sister. She has received rave reviews for her portrayal of Rehana Abidi in Alankrita Shrivastava's critically acclaimed Lipstick Under My Burkha. In 2020, she starred in the Amazon Prime web-series Breathe: Into the Shadows. The show was well-received by both audiences and critics. In 2021, she starred as Ayesha in the web series Bombay Begums, directed by Alankrita Shrivastava. She has recently played the lead role in the Zee5 series Sutliyan.`,
    Seema: `Seema Lokhandwala is an engineer turned elephant biologist who aims to integrate the latest technologies with data and concepts from elephant communication, behavior and ecology to understand the ecological and evolutionary processes that promote wildlife conservation. Her passion includes developing state of art acoustic sensors which aid in mitigating human-elephant conflict and facilitate peaceful coexistence. When not running behind or running away from elephants, she enjoys reading non-fiction novels based on environmental history, politics and wildlife. Seema is currently a PhD scholar at the Centre for Linguistic Science and Technology at the Indian Institute of Technology Guwahati.`

}



export default speaker2023Data;